"""AC25 — CLAUDE.md `@OPERATING.md` import contract (the "two CLAUDE.md", D8).

Two CLAUDE.md files matter (decision D8):
  1. the repo CLAUDE.md checked in on disk — imports OPERATING.md via an `@...` line;
  2. the machine-global ~/CLAUDE.md GENERATED by bin/install-operating-rules.sh —
     imports the repo's OPERATING.md by ABSOLUTE path.

Both assertions parse the actual `@` import line(s) from the file (no hardcoded path)
and assert the referenced OPERATING.md file EXISTS. The generated half is produced
in-test by running the installer into a fake HOME via _helpers.run_script.
"""
import re
from pathlib import Path

import _helpers


# An `@import` line in a Claude markdown file: `@` at line start, then a path token
# ending in OPERATING.md. Captures the path so we can resolve + existence-check it.
_OPERATING_IMPORT = re.compile(r"^@(\S*OPERATING\.md)\s*$", re.MULTILINE)


def _operating_imports(text):
    """Every `@<path>OPERATING.md` import path parsed from `text` (in order)."""
    return _OPERATING_IMPORT.findall(text)


# --------------------------------------------------------------------------- #
# Part 1 — the repo CLAUDE.md on disk
# --------------------------------------------------------------------------- #
def test_repo_claude_md_imports_operating(repo_root):
    """The repo's CLAUDE.md has an `@...OPERATING.md` import that resolves to an
    existing file (resolve relative to CLAUDE.md's own dir; absolute paths as-is)."""
    claude_md = repo_root / "CLAUDE.md"
    assert claude_md.is_file(), f"repo CLAUDE.md missing at {claude_md}"

    imports = _operating_imports(claude_md.read_text(encoding="utf-8"))
    assert imports, (
        "repo CLAUDE.md has no `@...OPERATING.md` import line — the operating "
        "rules would not apply"
    )

    # The import must resolve to THIS repo's canonical OPERATING.md — not merely to
    # some existing OPERATING.md elsewhere (a regression to `@/tmp/OPERATING.md` or
    # another clone's copy would otherwise pass).
    canonical = (repo_root / "OPERATING.md").resolve()
    for imp in imports:
        # `@OPERATING.md` is relative to CLAUDE.md's dir; an absolute `@/abs/...`
        # resolves to itself. Path() handles both via the parent join.
        resolved = (claude_md.parent / imp).resolve()
        assert resolved.is_file(), (
            f"CLAUDE.md imports `@{imp}` but {resolved} does not exist"
        )
        assert resolved == canonical, (
            f"CLAUDE.md import `@{imp}` resolves to {resolved}, not this repo's "
            f"canonical OPERATING.md at {canonical}"
        )


# --------------------------------------------------------------------------- #
# Part 2 — the installer-generated ~/CLAUDE.md (absolute import)
# --------------------------------------------------------------------------- #
def test_generated_global_claude_md_imports_absolute_operating(fake_home):
    """Running bin/install-operating-rules.sh writes ~/CLAUDE.md whose
    `@<abs>/OPERATING.md` import points at an existing ABSOLUTE OPERATING.md.

    This test owns the IMPORT contract only; AC20 owns the installer's overall
    behavior. So we do NOT gate on whole-installer exit 0 — an unrelated later step
    (skill/command symlinks, settings.json hook) failing must not mask the import
    contract, which the installer writes first. We still run the installer and
    surface its stderr on a non-zero exit for diagnostics, but key every assertion
    on the GENERATED import line resolving."""
    installer = _helpers.REPO_ROOT / "bin" / "install-operating-rules.sh"
    assert installer.is_file(), f"installer missing at {installer}"

    proc = _helpers.run_script(["bash", str(installer)], home=fake_home)
    installer_diag = (
        f"\n(installer exited {proc.returncode}\nstdout:\n{proc.stdout}\n"
        f"stderr:\n{proc.stderr})"
    )

    global_claude = fake_home / "CLAUDE.md"
    assert global_claude.is_file(), (
        f"installer did not write ~/CLAUDE.md (looked at {global_claude}){installer_diag}"
    )

    imports = _operating_imports(global_claude.read_text(encoding="utf-8"))
    assert imports, (
        f"generated ~/CLAUDE.md has no `@...OPERATING.md` import line{installer_diag}"
    )

    for imp in imports:
        assert imp.startswith("/"), (
            f"generated import `@{imp}` is not absolute — it must point at the "
            f"repo's OPERATING.md by absolute path so it resolves from any session"
            f"{installer_diag}"
        )
        assert Path(imp).is_file(), (
            f"generated ~/CLAUDE.md imports `@{imp}` but that file does not exist"
            f"{installer_diag}"
        )
        # It should point at THIS repo's OPERATING.md.
        assert Path(imp).resolve() == (_helpers.REPO_ROOT / "OPERATING.md").resolve(), (
            f"generated import `@{imp}` does not resolve to this repo's OPERATING.md"
            f"{installer_diag}"
        )
